const fictional_characterData = {
    category: "FICTIONAL CHARACTER",
    puzzles: [
        "A DAMSEL IN DISTRESS",
        "A GIANT ROBOT",
        "A HOWLING WEREWOLF",
        "A KNIGHT IN SHINING ARMOR",
        "A PHANTOM HOLDING A SICKLE",
        "A VAMPIRE FREAKING OUT AT A RAY OF SUNLIGHT",
        "ABBY SCIUTO",
        "ABOMINABLE SNOWMAN",
        "ABRAHAM WOODHULL",
        "ABUJA CALHOUN",
        "ACE VENTURA",
        "ACHILLES",
        "ADMIRAL WILLIAM ADAMA",
        "ADRIENNE WILLIS",
        "AGAMEMNON",
        "AGENT SMITH",
        "AL BUNDY",
        "AL DELVECCHIO",
        "AL SWEARENGEN",
        "ALADDIN",
        "ALBUS DUMBLEDORE",
        "ALCHEMIST",
        "ALEX CROSS",
        "ALEX DANVERS",
        "ALICE & THE MAD HATTER",
        "ALICE AND THE MAD HATTER",
        "ALICE KINGSLEIGH",
        "ALICE KINGSLEY",
        "ALICIA FLORRICK",
        "ALIEN CREATURES",
        "ALLISON POND",
        "ALLY DAWSON",
        "ALVIN & THE CHIPMUNKS",
        "ALVIN AND THE CHIPMUNKS",
        "AMANDA WALLER",
        "AMANDA WOODWARD",
        "AMAZING SHAPESHIFTERS",
        "AMELIA BEDELIA",
        "AMOS DECKER",
        "AMY FARRAH FOWLER",
        "AMY POEHLER AS JOY",
        "ANAKIN SKYWALKER",
        "ANASTASIA STEELE & CHRISTIAN GREY",
        "ANCIENT GREEK GODS",
        "ANDROMEDA",
        "ANDY CAPP",
        "ANDY SACHS",
        "ANGELA BENNETT",
        "ANGELA CHASE",
        "ANGELICA PICKLES",
        "ANN DARROW & KING KONG",
        "ANNA & ELSA",
        "ANNA SCOTT",
        "ANNE SHIRLEY",
        "ANNIE & GEORGE & MITCHELL",
        "ANNIE SAVOY & RAY KINSELLA",
        "ANNIE SAVOY AND RAY KINSELLA",
        "ANNIE WILSON",
        "ANTHONY BRIDGERTON",
        "ANTHONY DINOZZO",
        "ANT-MAN",
        "APHRODITE",
        "APHRODITE & ADONIS",
        "APHRODITE GODDESS OF LOVE",
        "APHRODITE GODDESS OF LOVE AND BEAUTY",
        "APHRODITE GODDESS OF THE LOVE & BEAUTY",
        "APHRODITE THE GODDESS OF LOVE & BEAUTY",
        "APOLLO",
        "APOLLO & CASSANDRA",
        "APOLLO GOD OF MUSIC",
        "APOLLO THE GOD OF SUN",
        "APOLLO THE GOD OF THE SUN",
        "AQUAMAN",
        "ARAGORN",
        "ARCHETYPE",
        "ARCHIE & JUGHEAD",
        "ARCHIE",
        "JUGHEAD",
        "BETTY",
        "& VERONICA",
        "ARI GOLD",
        "ARNOLD HORSHACK",
        "ARNOLD JACKSON",
        "ARTEMIS",
        "ARTEMIS THE GODDESS",
        "ARTHUR FONZARELLI",
        "ARYA AND THE HOUND",
        "ARYA STARK",
        "ASGARDIANS",
        "ASHLEY WALKER",
        "ASTRONAUT STEVE AUSTIN",
        "ASTRONAUT TONY NELSON",
        "ATHENA THE GODDESS OF WISDOM",
        "ATOMIC SKULL",
        "ATTICUS FINCH & SCOUT",
        "AUSTIN MOON",
        "AUSTIN POWERS",
        "AYLA",
        "AYRA AND THE HOUND",
        "BABAR",
        "BABY LUMA",
        "BACCHUS & ARIADNE",
        "BALDER & ODIN",
        "BAMBI",
        "BANANARAMA",
        "BANDERSNATCH",
        "BARBARA MAITLAND",
        "BARBIE & KEN",
        "BARNEY & BETTY RUBBLE",
        "BARNEY AND BETTY RUBBLE",
        "BARNEY FIFE & THELMA LOU",
        "BARNEY HEFNER",
        "BARNEY RUBBLE",
        "BARNEY THE PURPLE DINOSAUR",
        "BARON FEATHERINGTON",
        "BARON HELM",
        "BARON HELMUT ZEMO",
        "BART & LISA SIMPSON",
        "BART LISA & MAGGIE SIMPSON",
        "BART SIMPSON",
        "BARTENDER ISAAC WASHINGTON",
        "BATMAN",
        "BATMAN & ROBIN",
        "BATMAN AND ROBIN",
        "BATMAN VILLAIN SCARECROW",
        "BATWOMAN",
        "BAZOOKA JOE",
        "BEAUTIFUL HEROINE",
        "BEAUTIFUL PRINCESS",
        "BEAUTIFUL PRINCESSES & HANDSOME PRINCES",
        "BEAUTIFUL PRINCESSES AND HANDSOME PRINCES",
        "BEAVER CLEAVER",
        "BEAVIS",
        "BECKY THATCHER",
        "BELLA & EDWARD",
        "BELLAMY BLAKE",
        "BELOVED ICON",
        "BEN GRIMM",
        "BEN LINUS",
        "BEN REILLY",
        "BEN TALLMADGE",
        "BENJAMIN JONES",
        "BENVOLIO",
        "BEOWULF",
        "BERNARD LOWE",
        "BERT & ERNIE",
        "BETTY & BARNEY RUBBLE",
        "BETTY BOOP",
        "BETTY ROSS",
        "BETTY RUBBLE",
        "BEVERLY GOLDBERG",
        "BIG BAD WOLF",
        "BIG BIRD",
        "BIG BIRD",
        "BERT",
        "& ERNIE",
        "BIG NATE",
        "BIGFOOT",
        "BILBO BAGGINS",
        "BILL COMPTON & SOOKIE STACKHOUSE",
        "BILL THE LIZARD",
        "BILL TRUMAN & GRACE ADLER",
        "BINX BOLLING",
        "BIRDEE PRUITT",
        "BIRDMAN",
        "BIRDO & PAULINE",
        "BISCUIT THE DOG",
        "BIZARRO & BLACK ADAM",
        "BIZARRO AND BLACK ADAM",
        "BLACK BEAUTY",
        "BLACK BELT",
        "BLACK BOLT",
        "BLACK CAT",
        "BLACK KNIGHT",
        "BLACK PANTHER",
        "BLACK WIDOW",
        "BLACK ZERO & BRAINIAC",
        "BLACKJACK",
        "BLAKE CARRINGTON",
        "BLANCHE DUBOIS",
        "BLOSSOM BUBBLES & BUTTERCUP",
        "BLUE DRAGON VIDEO GAMES",
        "BO & LUKE DUKE",
        "BO DUKE",
        "BOB BELCHER",
        "BOB CRATCHIT",
        "BOBBIE JO BRADLEY",
        "BOBBY BRADY",
        "BONNIE BENNETT",
        "BOOGIEMAN",
        "BORIS AND NATASHA",
        "BORIS BADENOV & NATASHA FATALE",
        "BOSS HOGG",
        "BOWSER",
        "BOYD PRITCHETT",
        "BOZO THE CLOWN",
        "BRAVE PRINCE",
        "BRAVE RESCUERS",
        "BRENDA JOHNSON",
        "BRENDA MORGENSTERN",
        "BRENDA WALSH",
        "BRIAN GRIFFIN",
        "BROM BONES",
        "BROTHER & SISTER BART & LISA SIMPSON",
        "BRUCE WAYNE",
        "BRUCE WAYNE'S ALTER EGO BATMAN",
        "BUBBLES & DORY",
        "BUCK ROGERS",
        "BUCKY BARNES",
        "BUDDY THE ELF",
        "BUFFY & ANGEL",
        "BUGS BUNNY",
        "BULLDOG DRUMMOND",
        "BUSKERS",
        "BUZ MURDOCK",
        "BUZZ LIGHTYEAR",
        "BUZZ LIGHTYEAR & WOODY",
        "CABLE & STRYFE",
        "CACKLING WITCHES",
        "CALLIOPE THE MUSE",
        "CALVIN & HOBBES",
        "CALYPSO",
        "CAMERON HOWE",
        "CAMERON TUCKER",
        "CAMILLA THE CHICKEN",
        "CANDY CANADAY",
        "CAPATAIN BRITAIN",
        "CAPED CRUSADER",
        "CAPED CRUSADERS",
        "CAPTAIN AMERICA",
        "CAPTAIN BRITAIN",
        "CAPTAIN CAVEMAN",
        "CAPTAIN HIKARU SULU",
        "CAPTAIN HOOK",
        "CAPTAIN JACK SPARROW",
        "CAPTAIN JAMES T. KIRK",
        "CAPTAIN JEAN-LUC PICARD",
        "CAPTAIN KANGAROO",
        "CAPTAIN KATHRYN JANEWAY",
        "CAPTAIN KIRK",
        "CAPTAIN MARVEL",
        "CAPTAIN MERRILL STUBING",
        "CAPTAIN PHILLIP HOFFMAN",
        "CAPTAIN VIDEO",
        "CARE BEARS",
        "CARLTON THE DOORMAN",
        "CARMINE THE BIG RAGOO RAGUSA",
        "CAROL BRADY",
        "CAROL DANVERS",
        "CAROLINE CHANNING",
        "CARRIE & BIG",
        "CARRIE & MR. BIG",
        "CARRIE BRADSHAW",
        "CARRIE BRADSHAW & MR. BIG",
        "CARRIE MATHISON",
        "CARRIE MIRANDA CHARLOTTE & SAMANTHA",
        "CARRIE",
        "MIRANDA",
        "CHARLOTTE & SAMANTHA",
        "CASSIOPEIA",
        "CASTOR & POLLUX",
        "CATWOMAN",
        "CATWOMAN & THE PENGUIN",
        "CATWOMAN AND THE PENGUIN",
        "CAVEWOMAN",
        "CECE PAREKH",
        "CENTAUR",
        "CENTAURS & NYMPHS",
        "CEPHEUS",
        "CERBERUS THE THREE-HEADED DOG",
        "CERSEI LANNISTER",
        "CHACHI ARCOLA",
        "CHANDLER & PHOEBE",
        "CHARISMATIC CREATURES",
        "CHARLES INGALLS",
        "CHARLEY BROWN AND SNOOPY",
        "CHARLIE BROWN & SNOOPY",
        "CHARLIE BROWN SNOOPY & WOODSTOCK",
        "CHARLIE MCCARTHY",
        "CHARLIE PACE",
        "CHARLOTTE GRAYSON",
        "CHARLOTTE YORK",
        "CHESHIRE CAT",
        "CHESTER GOODE",
        "CHEWBACCA",
        "CHICKEN LITTLE",
        "CHIEF ANTAGONIST",
        "CHIEF JIM HOPPER",
        "CHIMPANZEES",
        "CHINESE CHECKERS",
        "CHIP & DALE",
        "CHIP DOUGLAS",
        "CHRISTMAS ELVES",
        "CHUCK & BLAIR",
        "CHUCK TODD",
        "CINDERELLA",
        "CINDERELLA & HER FAIRY GODMOTHER",
        "CINDERELLA & PRINCE CHARMING",
        "CINDERELLA AND PRINCE CHARMING",
        "CINDERELLA'S WICKED STEPSISTERS",
        "CINDY BRADY",
        "CINDY LOU WHO",
        "CINNAMON CARTER",
        "CINNAMON-RAISIN MUFFINS",
        "CLAIRE DUNPHY",
        "CLAIRE GIBBON",
        "CLAIRE LITTLETON",
        "CLAIRE UNDERWOOD",
        "CLARENCE ODBODY THE ANGEL",
        "CLARK & ELLEN GRISWOLD",
        "CLARK AND ELLEN GRISWOLD",
        "CLARK KENT",
        "CLARK KENT & LOIS LANE",
        "CLAYFACE",
        "CLEARANCE ODBODY THE ANGEL",
        "CLEM KADIDDLEHOPPER",
        "CLEVELAND BROWN",
        "CLIFF CLAVIN",
        "CLIFFORD THE BIG RED DOG",
        "CLIO THE MUSE",
        "CLYDE CRASHCUP",
        "COLONEL MUSTARD",
        "COLONEL SAUL TIGH",
        "COLORFUL UNICORN",
        "COLORFUL UNICORNS",
        "COLOSSUS",
        "COMET & CUPID",
        "COMET CUPID DONNER & BLITZEN",
        "COMIC BOOK SUPERHERO",
        "COMIC SIDEKICK",
        "COMIC-BOOK SUPERHERO",
        "COMMANDER WATERFORD",
        "COMPASSIONATE VILLAIN",
        "CONAN THE BARBARIAN",
        "CONQUISTADOR",
        "COOKIE MONSTER",
        "CORY & TOPANGA",
        "CORY AND TOPANGA",
        "COSMO SPACELY",
        "COSTUMED REVELER",
        "COUNT DRACULA",
        "COUNTRY MOUSE & CITY MOUSE",
        "COUNTRY MOUSE AND CITY MOUSE",
        "COUSIN ITT",
        "COVEN OF WITCHES",
        "CRAZY EYES",
        "CREATURE WITH SUPERNATURAL POWERS",
        "CREATURES FROM OUTER SPACE",
        "CREATURES OF THE NIGHT",
        "CREEPY CREATURES",
        "CREEPY MUMMY",
        "CRONUS",
        "CRUISE DIRECTOR JULIE MCCOY",
        "CUPID",
        "CUPID & COMET",
        "CUPID COMET",
        "CUPID THE GOD OF LOVE",
        "CURIOUS GEORGE",
        "CYCLOPS",
        "CYCLOPS & GORGONS",
        "CYLON NUMBER SIX",
        "DADDY WARBUCKS",
        "DAFFY DUCK",
        "DAGGER",
        "DAISY BUCHANAN",
        "DAISY DUKE",
        "DAME EDNA EVERAGE",
        "DAMON SALVATORE",
        "DAMSEL IN DISTRESS",
        "DAN RYDELL",
        "DANA SCULLY",
        "DANCING ELVES",
        "DANCING GOBLINS",
        "DANCING SKELETONS",
        "DANIEL PLAINVIEW",
        "DANNY PHANTOM",
        "DANNY ZUKO & SANDY OLSSON",
        "DAPHNE BASSETT",
        "DAPHNE MOON",
        "DAREDEVIL",
        "DAREDEVIL VILLAIN BULLSEYE",
        "DARIA MORGENDORFFER",
        "DARKWING DUCK",
        "DARRELL CARTRIP",
        "DARTH VADER",
        "DARTH VADER & LUKE SKYWALKER",
        "DASHER & DANCER",
        "DASHER DANCER PRANCER AND VIXEN",
        "DASHING HERO",
        "DAWSON",
        "DAYANARA DIAZ",
        "DEACON ERNEST FRYE",
        "DEE REYNOLDS",
        "DEITIES",
        "DEMETER & CERES",
        "DEMETER & PERSEPHONE",
        "DEMETER THE GODDESS OF HARVEST",
        "DEMETER THE GODDESS OF THE HARVEST",
        "DEMONS & TROLLS",
        "DENNIS THE MENACE",
        "DENNIS THE MENACE & MR. WILSON",
        "DERBY CLOWN JOE",
        "DESMOND HUME",
        "DETECTIVE ISAAC BELL",
        "DETECTIVE JANE RIZZOLI",
        "DEVILISH IMPS",
        "DEVILS & DEMONS",
        "DEVILS & VILLAINS",
        "DIANA & APOLLO",
        "DIANA PRINCE'S ALTER EGO WONDER WOMAN",
        "DIANA SKOURIS",
        "DIANE CHAMBERS",
        "DIANE FARROW",
        "DICK TRACY",
        "DIGITAL PETS",
        "DILLY THE DINOSAUR",
        "DIMINUTIVE DYNAMO WASP",
        "DIRTY HARRY",
        "DIRTY HARRY CALLAHAN",
        "DIVA PLAVALAGUNA",
        "DOCTOR DOLITTLE",
        "DOCTOR DOOM",
        "DOCTOR FRANKENSTEIN",
        "DOCTOR OCTOPUS",
        "DOCTOR WHO",
        "DODGE CHALLENGER",
        "DOLORES ABERNATHY",
        "DON DRAPER",
        "DON LOCKWOOD",
        "DON QUIXOTE",
        "DON QUIXOTE AND SANCHO PANZA",
        "DONALD & DAISY DUCK",
        "DONALD CRAGEN",
        "DONALD DUCK",
        "DONALD MALLARD",
        "DONALD SULLIVAN",
        "DONNER & BLITZEN",
        "DOOGIE HOWSER",
        "DOOMSDAY & GENERAL ZOD",
        "DORMAMMU",
        "DOROTHY AND TOTO",
        "DOROTHY BAXTER",
        "DOROTHY FROM THE WONDERFUL WIZARD OF OZ",
        "DOROTHY GALE",
        "DORY & NEMO",
        "DOT WARNER",
        "DOUBLE APPLE PIE WITH CORNMEAL CRUST",
        "DR MCCOY AND UHURA",
        "DR. ALEX KAREV",
        "DR. BRUCE BANNER",
        "DR. CHRISTIAN TROY",
        "DR. DOLITTLE",
        "DR. EMMETT BROWN",
        "DR. FRANKENSTEIN",
        "DR. FRANKENSTEIN'S ASSISTANT IGOR",
        "DR. JEKYLL AND MR. HYDE",
        "DR. MCCOY & UHURA",
        "DR. NICOLE HERMAN",
        "DR. NO",
        "DR. SHERMAN T. POTTER",
        "DR. SIVANA",
        "DR. ZAIUS",
        "DRACULA",
        "DRAGON & ELVES",
        "DRAGON QUEEN",
        "DRAGONS & ELVES",
        "DRAGONS & KNIGHTS",
        "DREAMERS & DOERS",
        "DREAMERS AND DOERS",
        "DUMBO THE ELEPHANT",
        "DUMBO THE FLYING ELEPHANT",
        "DWARVES GOBLINS & GNOMES",
        "DWIGHT K. SCHRUTE",
        "DWIGHT SCHRUTE",
        "DYNAMIC DUO",
        "EASTER BUNNY",
        "EB DAWSON",
        "EBENEZER SCROOGE",
        "ECHO & HERA",
        "ECHO & NARCISSUS",
        "ED & TRIXIE NORTON",
        "EDDIE BROCK",
        "EDDIE HASKELL",
        "EDDIE MARILYN LILY & HERMAN MUNSTER",
        "EDWARD MEECHUM",
        "EDWARD SCISSORHANDS",
        "EERIE GHOSTS",
        "EEYORE & PIGLET",
        "ELINOR DASHWOOD",
        "ELIZA THORNBERRY",
        "ELIZABETH JENNINGS",
        "ELIZABETH MCCORD",
        "ELLEN RIPLEY",
        "ELLIOT STABLER",
        "ELLIS BOYD REDDING",
        "ELLY MAY CLAMPETT",
        "ELMER FUDD",
        "ELOISE BRIDGERTON",
        "ELPHABA THROPP",
        "ELVES & DWARVES",
        "ELVES & FAIRIES",
        "ELVES & GNOMES",
        "ELVES PIXIES & FAIRIES",
        "ELVES PIXIES AND FAIRIES",
        "EMILY ELIZABETH",
        "EMMA SWAN",
        "ENCHANTED PRINCESS",
        "ENCHANTING FAIRY",
        "ENCHANTRESS",
        "ENERGIZER BUNNY",
        "ENTOURAGE'S TURTLE",
        "ERATO THE MUSE",
        "ERIC CARTMAN",
        "ERIC MURPHY",
        "ERIC TAYLOR",
        "EROS & CUPID",
        "EROS & PSYCHE",
        "EROS AND PSYCHE",
        "EROS GOD OF LOVE",
        "EROS THE GREEK GOD OF LOVE",
        "ETHAN HUNT",
        "ETHAN WHITEHORSE",
        "EVELYN POWELL",
        "EVIL GENIUS",
        "EVIL JESTER",
        "EVIL KING",
        "EVIL QUEEN",
        "EVIL SCIENTIST",
        "EVIL TROLLS",
        "EVIL VILLAIN",
        "EVIL VILLAN",
        "FAIRIES & ELVES",
        "FAIRY DUST BUNNIES",
        "FAIRY GODMOTHER",
        "FAIRY PRINCESS",
        "FAIRY-TALE PRINCESS",
        "FANTASTIC CREATURE",
        "FANTASTIC MR. FOX",
        "FAT ALBERT",
        "FATHER CHRISTMAS",
        "FATHER KNOWS BEST",
        "FATHER TIME",
        "FATHER-IN-LAW",
        "FEARSOME CREATURES",
        "FEEDING SHARKS",
        "FELIX THE CAT",
        "FELIX UNGER",
        "FERDINAND THE FAITHFUL",
        "FERRIS BUELLER",
        "FEZZIWIG",
        "FICTIONAL CHARACTER",
        "FICTIONAL CREATURE",
        "FIGURE COMPETITION",
        "FINE TOOTH COMB",
        "FINN & REY",
        "FIONA GOODE",
        "FIONNA GOODE",
        "FIRE BREATHING DRAGON",
        "FIRE BREATHING FLYING DRAGONS",
        "FIRE-BREATHING DRAGON",
        "FIRE-BREATHING DRAGONS",
        "FIRE-BREATHING FLYING DRAGONS",
        "FIRE-BREATHING THREE-HEADED DRAGON",
        "FLASH THOMPSON",
        "FLAT STANLEY",
        "FLORENCE JEAN “FLO” CASTLEBERRY",
        "FLORENCE JEAN FLO CASTLEBERRY",
        "FLOWER FAIRIES",
        "FLYING BEAST & MAGICAL CREATURES",
        "FLYING BEASTS",
        "FLYING BEASTS & MAGICAL CREATURES",
        "FLYING BEASTS AND MAGICAL CREATURES",
        "FLYING REINDEER",
        "FLYNN RIDER",
        "FOGHORN LEGHORN",
        "FORMER CHIEFS OF STAFF",
        "FORREST GUMP",
        "FORTUNE ROSE GIBBON",
        "FOX MULDER",
        "FOX MULDER & DANA SCULLY",
        "FOZZIE BEAR",
        "FRANK BULLIT",
        "FRANK BULLITT",
        "FRANK DEFAZIO",
        "FRANK UNDERWOOD",
        "FRANKENSTEIN",
        "FRANKENSTEIN & DRACULA",
        "FRASIER CRANE",
        "FREAKISH FIEND",
        "FRED & ETHEL MERTZ",
        "FRED & LAMONT SANFORD",
        "FRED FLINSTONE & BARNEY RUBBLE",
        "FRED FLINTSTONE",
        "FRED FLINTSTONE & BARNEY RUBBLE",
        "FRED FLINTSTONE'S BOSS MR. SLATE",
        "FRED G. SANFORD",
        "FRED",
        "DAPHNE",
        "VELMA",
        "AND SHAGGY",
        "FREDDY KRUEGER",
        "FRENCH STEWART AS HARRY SOLOMON",
        "FREY & FREYA",
        "FRIAR TUCK",
        "FRIENDLY ALIEN",
        "FRIENDLY CLOWNS",
        "FRIENDLY EXTRA-TERRESTRIALS",
        "FRIENDLY MONSTER",
        "FRIGHTENING CREATURES",
        "FRIGHTENING PHANTOM",
        "FRIGHTENING PHANTOMS",
        "FRIGHTENING ZOMBIES",
        "FRIGHTFUL GOBLINS",
        "FRIGHTFUL OGRE",
        "FRODO & BILBO",
        "FRODO AND BILBO",
        "FRODO BAGGINS",
        "FROLICKING ELVES",
        "FROST GIANTS",
        "FROSTY THE SNOWMAN",
        "FROSTY THE SNOWMAN & SANTA CLAUS",
        "FROSTY THE SNOWMAN AND SANTA CLAUS",
        "FUNSHINE BEAR",
        "FUNSHINE BEARS",
        "G.I. JOE",
        "GABE KOTTER",
        "GABE MOTHER",
        "GABI DIAMOND",
        "GAEA & OCEANUS",
        "GAEA THE GODDESS OF THE EARTH",
        "GALACTUS",
        "GALADRIEL",
        "GALE HAWTHORNE",
        "GAMBIT",
        "GANDALF THE WIZARD",
        "GARGOYLE",
        "GARGOYLES & WITCHES",
        "GEICO GECKO",
        "GENEVIEVE DELATOUR",
        "GENIE IN A BOTTLE",
        "GEORGE & LOUISE JEFFERSON",
        "GEORGE ALTMAN",
        "GEORGE COSTANZA",
        "GEORGE JANE ELROY & JUDY JETSON",
        "GEORGE OF THE JUNGLE",
        "GEORGE TAYLOR",
        "GEORGIA ON MY MIND BY RAY CHARLES",
        "GEORGIE PORGIE",
        "GERALD – MCBOING BOING",
        "GHASTLY GOBLINS",
        "GHOST OF CHRISTMAS FUTURE",
        "GHOST OF CHRISTMAS PAST",
        "GHOST PIRATE",
        "GHOST PIRATES",
        "GHOST RIDER",
        "GHOSTLY APPARITION",
        "GHOSTS & GOBLINS",
        "GIANT MONSTERS",
        "GIANT SPIDERS",
        "GIANT YETI",
        "GIDGET",
        "GIGGLING GHOULS",
        "GILLIGAN & THE SKIPPER",
        "GINA WATERS-PAYNE",
        "GINGER & MARY ANN",
        "GINGER AND MARY ANN",
        "GINNY WEASLEY",
        "GIZMO",
        "GIZMO & STRIPE",
        "GLINDA THE GOOD WITCH",
        "GLORIA DELGADO-PRITCHETT",
        "GLORIA MENDOZA",
        "GLORIA MUNDY",
        "GNOMES & FAIRIES",
        "GNOMES & GOBLINS",
        "GNOMES & LEPRECHAUNS",
        "GNOMES AND FAIRIES",
        "GNOMES AND LEPRECHAUNS",
        "GOBLIN PRINCE",
        "GOBLINS & FAIRIES",
        "GOBLINS & GARGOYLES",
        "GOBLINS & GIANTS",
        "GOBLINS & MONSTERS",
        "GOD OF THUNDER",
        "GODDESS HATHOR",
        "GODDESS LIBERTAS",
        "GODZILLA",
        "GOLDILOCKS",
        "GOLDILOCKS AND THE THREE BEARS",
        "GOMER & GOOBER PYLE",
        "GOMER PYLE",
        "GOMEZ & MORTICIA ADDAMS",
        "GOMEZ ADDAMS",
        "GONZO THE GREAT",
        "GOOBER PYLE",
        "GOOFY & DONALD DUCK",
        "GORILLA GRODD",
        "GOTHAM CITY'S COMMISSIONER GORDON",
        "GRACE HANSON",
        "GRACE KING BICHON",
        "GRANDMAMA ADDAMS",
        "GREEK GODDESS APHRODITE",
        "GREEK GODS",
        "GREEK GODS & GODDESSES",
        "GREEK GODS AND GODDESS",
        "GREEK HEROES",
        "GREEN ARROW",
        "GREEN GOBLIN",
        "GREEN LANTERN",
        "GREEN MONSTERS",
        "GREG BRADY",
        "GREG PETER & BOBBY BRADY",
        "GREG PETER AND BOBBY BRADY",
        "GREGOR CLEGANE",
        "GREGORE CLEGANE",
        "GRIFFIN",
        "GRIGORY RASPUTIN",
        "GRIM REAPER",
        "GROGOR CEGANE",
        "GROVER & OSCAR THE GROUCH",
        "GUILDENSTERN",
        "GUMBY",
        "GUMBY & POKEY",
        "HADES KING OF THE UNDERWORLD",
        "HADES THE GOD OF THE NETHERWORLD",
        "HAKEEM LYON",
        "HAL MASON",
        "HAMLET",
        "HAN SOLO & CHEWBACCA",
        "HANDSOME PRINCE",
        "HANDSOME SUITORS",
        "HANK HENSHAW",
        "HANK HILL",
        "HANK MCCOY",
        "HANK PYM",
        "HANNAH HORVATH AND MARNIE MICHAELS",
        "HANNIBAL LECTER",
        "HANSEL & GRETEL",
        "HAPPY & GRUMPY",
        "HARLEY QUINN",
        "HAROLD HILL",
        "HARRIET THE SPY",
        "HARRY & SALLY",
        "HARRY BURNS & SALLY ALBRIGHT",
        "HARRY DAVIS",
        "HARRY POTTER",
        "HARVEY SPECTER",
        "HAWKEYE",
        "HAWKEYE PIERCE",
        "HEADLESS HORSEMAN",
        "HEATH BARKLEY",
        "HECKLE & JECKLE",
        "HECKLE AND JECKLE",
        "HELEN CRUMP",
        "HELIOS & PHAETHON",
        "HELLO KITTY",
        "HENRY CAVILL AS THE MAN OF STEEL",
        "HENRY HIGGINS",
        "HENRY MILLS",
        "HERBIE THE LOVE BUG",
        "HERCULE POIROT",
        "HERCULES",
        "HERCULES & ZEUS",
        "HERCULES POIROT",
        "HERMAN & LILY MUNSTER",
        "HERMES & APOLLO",
        "HERMES MESSENGER OF THE GODS",
        "HERMIONE GRANGER",
        "HEROES & GODS",
        "HESTIA GODDESS",
        "HESTIA GODDESS OF FAMILY",
        "HIGH SCHOOL MASCOT",
        "HIGH SPARROW",
        "HOBGOBLIN",
        "HOBGOBLINS",
        "HODOR",
        "HOLDEN CAUFIELD",
        "HOLDEN CAULFIELD",
        "HOLLY HUNTER AS ELASTIGIRL",
        "HOMER",
        "HOMER & MARGE SIMPSON",
        "HOMER SIMPSON",
        "HOP SING",
        "HOUSE STARK",
        "HOWARD & BERNADETTE",
        "HOWARD CUNNINGHAM",
        "HOWARD THE DUCK",
        "HOWLING PHANTOM",
        "HOWLING PHANTOMS",
        "HOWLING WEREWOLVES",
        "HUCKLEBERRY HOUND",
        "HUEY DEWEY & LOUIE",
        "HUEY DEWEY AND LOUIE",
        "HUGINN & MUNINN",
        "HULK VILLAIN ABOMINATION",
        "HUMANITY-PROTECTING GOD THOR",
        "HUMPTY DUMPTY",
        "HUNGRY ZOMBIE",
        "HUNGRY ZOMBIES",
        "HUNTER ROSE",
        "HYACINTH BRIDGERTON",
        "HYDRA",
        "ICARUS & DAEDALUS",
        "ICE GIANTS",
        "ICEMAN",
        "ICHABOD CRANE",
        "ICONIC SUPERHEROES",
        "IDUN",
        "IMAGINARY FRIEND",
        "IMAGINARY FRIENDS",
        "INDIANA JONES",
        "INSPECTOR GADGET",
        "INSPECTOR JACQUES CLOUSEAU",
        "INVISIBLE MAN",
        "IZUKU MIDORIYA",
        "JABBA THE HUTT",
        "JABBERJAW",
        "JACK & JILL",
        "JACK BAUER",
        "JACK FROST",
        "JACK SHEPHARD",
        "JACK SPRAT",
        "JACK TRIPPER & JANET WOOD",
        "JACOB MARLEY",
        "JADE EMPEROR",
        "JAIME LANNISTER",
        "JAKE & ELWOOD BLUES",
        "JAKE & SAMANTHA FROM SIXTEEN CANDLES",
        "JAMES BOND",
        "JAMES GORDON",
        "JAMES OLSEN",
        "JAMES P SULLIVAN",
        "JAMES P. SULLIVAN",
        "JAN BRADY",
        "JANE JETSON",
        "JANET VAN DYNE",
        "JANET WEISS & BRAD MAJORS",
        "JAR JAR BINKS",
        "JASON & THE ARGONAUTS",
        "JASON VOORHEES",
        "JASPER JORDAN",
        "JAY GATSBY",
        "JEAN CABOT",
        "JEAN GREY",
        "JEAN VALJEAN",
        "JED CLAMPETT",
        "JEDI KNIGHT",
        "JEKYLL",
        "JEKYLL & HYDE",
        "JEMMA SIMMONS",
        "JERRY GEORGE KRAMER & ELAINE",
        "JESSE & CELINE",
        "JESSICA JONES",
        "JESSICA JONES & LUKE CAGE",
        "JESSICA PEARSON",
        "JESSICA RABBIT",
        "JETHRO BODINE",
        "JETT JACKSON",
        "JIMINY CRICKET",
        "JIN-SOO KWON",
        "JO POLNIACZEK",
        "JOE FRIDAY",
        "JOE HAWKINS",
        "JOE MACMILLAN",
        "JOE MANNIX",
        "JOEY ROONEY",
        "JOFFREY BARATHEON",
        "JOHN BOSWORTH",
        "JOHN COFFEY",
        "JOHN CONSTANTINE",
        "JOHN MCCLANE",
        "JOHN MUNCH",
        "JOHN-BOY WALTON",
        "JOHNNY CAT",
        "JOHNNY STORM",
        "JOLLY ELVES",
        "JOLLY LITTLE ELF",
        "JOLLY OLD SAINT NICHOLAS",
        "JOLLY OLD SAINT NICK",
        "JOLLY OLD ST. NICK",
        "JON OSTERMAN",
        "JONATHAN BYERS",
        "JUAN EPSTEIN",
        "JUDGE DREDD",
        "JUDY JETSON",
        "JUGGERNAUT",
        "JULES WINNFIELD",
        "JULIA MCNAMARA",
        "JULIE POWELL",
        "JULIET BURKE",
        "JUMPING OUT & SCREAMING BOO!",
        "JUNE CLEAVER",
        "JUNE JETSON",
        "JUNO THE GODDESS OF MARRIAGE",
        "JUNO THE QUEEN OF THE GODS",
        "JUNO: GODDESS OF WOMEN",
        "JUPITER & JUNO",
        "JUPITER AND JUNO",
        "JUPITER KING OF THE GODS",
        "JUPITER THE KING OF THE GODS",
        "JUPITOR & JUNO",
        "K",
        "KANALOA HAWAIIAN GOD OF THE OCEAN",
        "KAREN ROONEY",
        "KAREN WALKER",
        "KARL & SUSAN KENNEDY",
        "KAT STRATFORD",
        "KATE AUSTEN",
        "KATE AUSTEN & JACK SHEPHARD",
        "KATE BECKET",
        "KATE BECKETTE",
        "KATE BRADLEY",
        "KATHERINE WATSON",
        "KATNISS EVERDEEN",
        "KAY SCARPETTA",
        "KEL KIMBLE",
        "KEN & RYU",
        "KENAN ROCKMORE",
        "KERMIT THE FROG",
        "KERMIT THE FROG & FIZZ IS BEAR",
        "KERMIT THE FROG & FOZZIE BEAR",
        "KERMIT THE FROG & MISS PIGGY",
        "KERMIT THE FROG AND MISS PIGGY",
        "KEVIN & WINNIE",
        "KEVIN FICTIONAL CHARACTER KEVIN FLYNN",
        "KEVIN GARVEY",
        "KEVIN SPACEY",
        "KID MARVELMAN",
        "KIKI HARRISON",
        "KIM & EDWARD",
        "KIM POSSIBLE",
        "KIM WEXLER",
        "KIMBER HENRY",
        "KING ARTHUR",
        "KING ARTHUR & THE KNIGHTS OF THE ROUND TABLE",
        "KING ARTHUR AND HIS KNIGHTS",
        "KING CANDY",
        "KING ECBERT",
        "KING KONG",
        "KING KONG & GODZILLA",
        "KING LEAR",
        "KING LEODEGRANCE",
        "KING MIDAS",
        "KING OF HEARTS",
        "KING OF THE GODS",
        "KING PELLINORE",
        "KINGS QUEENS PRINCES & PRINCESSES",
        "KITCHEN GOD",
        "KITTY PRYDE",
        "KNAVE OF HEARTS",
        "KNIGHT IN SHINING ARMOR",
        "KNIGHT ON A WHITE HORSE",
        "KNIGHTS & DRAGONS",
        "KNIGHTS OF THE KINGDOM",
        "KNIGHTS OF THE ROUND TABLE",
        "KOLOTH",
        "KRAVEN THE HUNTER",
        "KRIS KRINGLE",
        "KRISTOFF & OLAF",
        "KRISTY MCNICHOL",
        "KURT HUMMEL & BLAINE ANDERSON",
        "KYLE & HYDE",
        "KYLE VALENTI",
        "KYLO REN",
        "LADY CAPULET",
        "LADY CHATTERLEY",
        "LADY DANBURY",
        "LADY JUSTICE",
        "LADY MACBETH",
        "LADY OF THE LAKE",
        "LARA CROFT",
        "LARRY MOE & CURLY",
        "LASSIE",
        "LATIKA & JAMAL",
        "LAUGHING WICKED WITCH",
        "LAURA BURNEY",
        "LAURA INGALLS & ALMANZO WILDER",
        "LAURA PETRIE",
        "LAURIE GARVEY",
        "LAVA CREATURES",
        "LAVERNE DEFAZIO",
        "LAVINIA KINGSLEY",
        "LAWYER BILLY FLYNN",
        "LEGENDARY SEA MONSTERS",
        "LEIA ORGANA",
        "LENNY & SQUIGGY",
        "LEONARD HOFSTADTER",
        "LEPRECHAUN",
        "LEPRECHAUN SITTING ON A POT OF GOLD",
        "LEPRECHAUNS",
        "LEROY JETHRO GIBBS",
        "LESTER NYGAARD",
        "LIGHTNING BUGS",
        "LILY MUNSTER",
        "LILY POTTER",
        "LINDA BELCHER",
        "LISA DOUGLAS",
        "LISA SIMPSON",
        "LITTLE BO PEEP",
        "LITTLE BO-PEEP",
        "LITTLE BOY BLUE",
        "LITTLE GREEN MEN FROM MARS",
        "LITTLE JACK HORNER",
        "LITTLE LEPRECHAUNS",
        "LITTLE LULU",
        "LITTLE MISS MUFFET",
        "LITTLE ORPHAN ANNIE",
        "LITTLE ORPHAN ANNIE & SANDY",
        "LITTLE RED RIDING HOOD",
        "LITTLE RED RIDING HOOD & HER GRANDMOTHER",
        "LITTLE RED RIDING HOOD AND HER GRANDMOTHER",
        "LITTLE RED RIDING HOOD'S GRANDMOTHER",
        "LITTLE TOMMY TUCKER",
        "LIV ROONEY",
        "LIZARD & LEADER",
        "LOCH NESS MONSTER",
        "LOGAN MOUNTSTUART",
        "LOIS LANE",
        "LOIS LANE & CLARK KENT",
        "LOKI",
        "LONE RANGER & TONTO",
        "LONE RANGER'S SIDEKICK TONTO",
        "LONG JOHN SILVER",
        "LONG-NOSED TROLL",
        "LORD VOLDEMORT",
        "LORDS OF WINTERFELL",
        "LORELAI GILMORE",
        "LOU GRANT & TED BAXTER",
        "LOUISE JEFFERSON",
        "LOVELY PRINCESS",
        "LUCAS BISHOP",
        "LUCILLE BLUTH",
        "LUCKY ELVES",
        "LUCY & LINUS",
        "LUCY & SCHROEDER",
        "LUCY AND LINUS",
        "LUCY CARTER",
        "LUCY ELEANOR MODERATZ",
        "LUCY LINUS SCHROEDER AND CHARLIE BROWN",
        "LUCY PEVENSIE",
        "LUCY RICARDO",
        "LUCY VAN PELT",
        "LUIGI & PRINCESS PEACH",
        "LUKE CAGE",
        "LUKE CAGE & JESSICA JONES",
        "LUKE DUKE",
        "LUKE SKYWALKER",
        "LUKE SKYWALKER & PRINCESS LEIA",
        "LUNA LOVEGOOD",
        "LURCH THE BUTLER",
        "LURKING GHOULS",
        "LYANNA STARK",
        "MAD MAX",
        "MAD SCIENTIST",
        "MAEVE MILLAY",
        "MAGGIE CARPENTER",
        "MAGICAL CREATURES",
        "MAGICAL ENGLISH NANNY",
        "MAGICAL GNOMES",
        "MAGICAL PIXIES",
        "MAGICAL WOOD CREATURES",
        "MAGILLA GORILLA",
        "MAID MARIAN",
        "MAIN ANTAGONIST",
        "MAJOR HEWLETT",
        "MAKE-BELIEVE BEAST",
        "MAKE-BELIEVE BEASTS",
        "MAKE-BELIEVE CREATURES",
        "MAKE-BELIEVE FRIEND",
        "MALCOLM MERLYN",
        "MALEAGANT",
        "MALORY ARCHER",
        "MAMA BEAR",
        "MAMA BEAR PAPA BEAR & BABY BEAR",
        "MAN IN THE YELLOW HAT",
        "MANNY DELGADO",
        "MANY RARE BIRDS",
        "MARCH HARE",
        "MARCIA BRADY",
        "MARCIA JAN & CINDY BRADY",
        "MARCUS KANE",
        "MARCUS WELBY",
        "MARGAERY TYRELL",
        "MARGARET HARWOOD",
        "MARGE & HOMER SIMPSON",
        "MARGE SIMPSON",
        "MARIA & TONY",
        "MARILYN MUNSTER",
        "MARIO & DONKEY KONG",
        "MARIO & LUIGI",
        "MARISOL SUAREZ",
        "MARK",
        "MARK WATNEY",
        "MARLON BRANDO",
        "MARMADUKE",
        "MARS THE GOD OF WAR",
        "MARTIN RIGGS",
        "MARY BENNET",
        "MARY ELLEN WALTON",
        "MARY JANE & PETER",
        "MARY POPPINS",
        "MARY RICHARDS",
        "MARY WOODHULL",
        "MATILDA",
        "MATT JAMISON",
        "MAUDE FLANDERS",
        "MAX & THE WILD THINGS",
        "MAX BLACK",
        "MAX EVANS",
        "MAX ROBY",
        "MAXWELL SMART",
        "ME. PERFECT",
        "MEADOW AND AJ SOPRANO",
        "MEG MURRY & CALVIN O'KEEFE",
        "MEG MURRY AND CALVIN O'KEEFE",
        "MEGAN HUNT",
        "MEL SHARPLES",
        "MENACING MONSTERS",
        "MEPHISTO",
        "MERA & AQUAMAN",
        "MERA AND AQUAMAN",
        "MERLIN",
        "MERLIN THE MAGICIAN",
        "MERMAIDS & MERMEN",
        "MICHAEL & JAY KYLE",
        "MICHAEL DAWSON",
        "MICHAEL KYLE",
        "MICHAEL MYERS",
        "MICHAEL MYERS & JASON VOHREES",
        "MICHAEL MYERS & JASON VOORHEES",
        "MICKEY & MINNIE MOUSE",
        "MICKEY HALLER",
        "MICKEY MOUSE",
        "MICKEY MOUSE & PLUTO",
        "MIGHTY MORPHIN POWER RANGERS",
        "MIGHTY MOUSE",
        "MIKE BIGGS",
        "MIKE BRADY",
        "MIKE DOONESBURY",
        "MIKE WAZOWSKI",
        "MILBURN DRYSDALE",
        "MILES MORALES",
        "MILES ROBY",
        "MILHOUSE VAN HOUTON",
        "MILO MINDERBINDER",
        "MIMI BOBECK",
        "MINERVA & NEPTUNE",
        "MINERVA MCGONAGALL",
        "MINNIE MOUSE",
        "MINNIE MOUSE AND MICKEY MOUSE",
        "MINOTAUR",
        "MINOTAURS & DRAGONS",
        "MIRANDA HOBBES",
        "MIRANDA PRIESTLY",
        "MIRANDA TATE",
        "MIRROR MAN",
        "MIRROR MASTER",
        "MISCHEVIOUS SPRITES",
        "MISCHIEVOUS GOBLINS",
        "MISCHIEVOUS GREMLINS",
        "MISCHIEVOUS SPRITES",
        "MISS JANE HATHAWAY",
        "MISS MALLARD",
        "MISS MARPLE",
        "MISS MUFFET",
        "MISS MUFFETT",
        "MISS PIGGY",
        "MISS SCARLET & COLONEL MUSTARD",
        "MISTER IMMORTAL",
        "MISTER SINISTER",
        "MOLLY WEASLEY",
        "MOLTEN MAN",
        "MONSTERS & MUMMIES",
        "MONSTERS & OGRES",
        "MONSTERS & VAMPIRES",
        "MOON JELLIES",
        "MORGANA PENDRAGON",
        "MORGANA THE SORCERESS",
        "MORRIS THE CAT",
        "MORTICIA & GOMEZ ADDAMS",
        "MOTHER EARTH",
        "MOTHER GINGER",
        "MOTHER GOOSE",
        "MOTHER NATURE",
        "MOUNTAIN TROLL",
        "MOVIE MONSTERS",
        "MR. BIG",
        "MR. BUBBLE",
        "MR. DARCY",
        "MR. FANTASTIC",
        "MR. INCREDIBLE",
        "MR. MAGOO",
        "MR. POOPER",
        "MR. SPOCK",
        "MRS. CLAUS",
        "MRS. MALAPROP",
        "MRS. PEACOCK",
        "MRS. PEPPER",
        "MRS. ROBINSON",
        "MUGGLES & WIZARDS",
        "MUGGLES AND WIZARDS",
        "MULAN",
        "MULDER & SCULLY",
        "MURIEL PRITCHETT",
        "MURPHY BROWN",
        "MUSE OF ASTRONOMY",
        "MUTANT X",
        "MUTANT-HUNTING ROBOT SENTINEL",
        "MUTANT-HUNTING ROBOT SENTINELS",
        "MY FAVORITE SUPERHERO",
        "MYRTLE WILSON",
        "MYSTERIOUS GOBLIN",
        "MYSTERIOUS MUMMIES",
        "MYSTIQUE & SABRETOOTH",
        "MYTHICAL BEAST",
        "MYTHICAL BEASTS",
        "MYTHICAL CREATURE",
        "MYTHICAL CREATURES",
        "MYTHICAL GODDESS ATHENA",
        "MYTHOLOGICAL ANIMALS",
        "MYTHOLOGICAL CREATURE",
        "MYTHOLOGICAL CREATURES",
        "MYTHOLOGICAL GOD ZEUS",
        "MYTHOLOGICAL HERO HERCULES",
        "NANCY & SLUGGO",
        "NANCY DREW",
        "NAOMI & WYNONNA JUDD",
        "NAOMI CLARK",
        "NARROW TWO-LANE ROAD",
        "NATHAN DRAKE",
        "NATHAN WINTERS",
        "NAUSICAA",
        "NAUSSICAA",
        "NED STARK",
        "NEED STARK",
        "NEPTUNE",
        "NEPTUNE GOD OF THE SEA",
        "NEPTUNE ROMAN GOD OF THE SEA",
        "NEREIDS",
        "NEW TEEN TITANS",
        "NICK CARRAWAY",
        "NICK FURY",
        "NICK MILLER",
        "NIGHTCRAWLER",
        "NIGHTCRAWLER & CYCLOPS",
        "NINJA WARRIOR",
        "NIPPER THE RCA DOG",
        "NOLAN ROSS",
        "NORM PETERSON",
        "NORMA SPEAKMAN",
        "NORMAN BATES",
        "NORMAN OSBORN",
        "NOTORIOUS VILLAINS",
        "NUMBER SIX",
        "NYMPHS & CENTAURS",
        "OBI-WAN KENOBI",
        "ODAFIN TUTUOLA",
        "ODDA THE YOUNGER",
        "ODIN & THOR",
        "ODYSSEUS & THE CYCLOPS",
        "ODYSSEUS AND THE CYCLOPS",
        "OFFICER CARL MCMILLAN",
        "OFFICER DIBBLE",
        "OFFICER GUNTHER TOODY",
        "OFFICER LEO SCHNAUSER",
        "OFFICER PETE MALLOY",
        "OGRE & TROLLS",
        "OGRES & GIANTS",
        "OGRES & TROLLS",
        "OLAF THE SNOWMAN",
        "OLD KING COLE",
        "OLD MOTHER HUBBARD",
        "OLIVE OYL",
        "OLIVER PLEXICO",
        "OLIVER TWIST",
        "OLIVIA POPE",
        "OLYMPIAN GODS",
        "ONE-EYED CYCLOPS",
        "OPIE TAYLOR",
        "OPUS THE PENGUIN",
        "ORORO MONROE",
        "ORORO MUNROE",
        "OSAFI TUTUOLA",
        "OSCAR MADISON",
        "OSCAR THE GROUCH",
        "OTHERWORDLY BEINGS",
        "OTHERWORLDLY BEINGS",
        "OTHERWORLDLY CREATURE",
        "OTHERWORLDLY CREATURES",
        "OZYMANDIAS",
        "PACEY & JOEY",
        "PAC-MAN",
        "PAC-MAN & MS. PAC-MAN",
        "PAC-MAN GHOSTS",
        "PADDINGTON BEAR",
        "PAGAN GODS",
        "PANDORA",
        "PANSY PARKINSON",
        "PAPA & BRAINY SMURF",
        "PAPA BEAR",
        "PAPA SMURF",
        "PAPA SMURF & GROUCHY SMURF",
        "PAPA SMURF & SMURFETTE",
        "PAPA SMURF & THE SMURFETTE",
        "PARADISE VALLEY MONTANA",
        "PARANORMAL INVESTIGATION TEAM",
        "PARK MASCOT",
        "PARKER ROONEY",
        "PATRICK STAR AND SQUIDWARD TENTACLES",
        "PATTY FENN",
        "PAUL BLART",
        "PAUL BUNYAN",
        "PAUL BUNYAN & BABE THE BLUE OX",
        "PAUL MCCARTNEY",
        "PAVEL CHEKOV",
        "PEACH & CRUSH",
        "PEBBLES & BAM BAM",
        "PEBBLES & BAMM BAMM",
        "PEETA & KATNISS",
        "PEGASUS",
        "PEGASUS THE WINGED HORSE",
        "PEGGY BUNDY",
        "PEGGY OLSON",
        "PEGGY OLSON & DON DRAPER",
        "PEGGY OLSON AND DON DRAPER",
        "PENANCE",
        "PENELOPE GARCIA",
        "PENNY & LEONARD",
        "PENNYWISE THE CLOWN",
        "PEPE LE PEW",
        "PEPPERMINT PATTY",
        "PERRY MASON",
        "PERSEPHONE",
        "PERSEPHONE THE GODDESS QUEEN OF THE UNDERWORLD",
        "PETER & LOIS GRIFFIN",
        "PETER AND JANE FONDA",
        "PETER BRADY",
        "PETER COTTONTALE",
        "PETER PAN",
        "PETER PARKER",
        "PETER PARKER AND MARY JANE WATSON",
        "PETER PETER PUMPKIN EATER",
        "PETER PIPER",
        "PETER RABBIT",
        "PETER RABBIT & MR. MCGREGOR",
        "PETUNIA PIG",
        "PHANTOM OF THE OPERA",
        "PHIL & CLAIRE FOSTER",
        "PHIL DUNPHY",
        "PHILIP & VIVIAN BANKS",
        "PHILIP JENNINGS",
        "PHILIPPA FEATHERINGTON",
        "PHOENIX FORCE",
        "PICCOLO",
        "PIGLET & EEYORE",
        "PIGPEN",
        "PINOCCHIO",
        "PINOCCHIO & GEPPETTO",
        "PIPER CHAPMAN",
        "PIPPI LONGSTOCKING",
        "PIRATES & NINJAS",
        "PIT ROAST",
        "PLAYFUL ELVES",
        "PLAYFUL GNOMES",
        "PLAYFUL TROLLS",
        "POCAHONTAS",
        "POKEMON",
        "POLLYANNA",
        "POLONIUS & CLAUDIUS",
        "POLYPHEMUS",
        "POOCH",
        "POPEYE & OLIVE OYL",
        "POPEYE THE SAILOR MAN",
        "PORKY & PETUNIA PIG",
        "PORKY PIG",
        "POSEIDON",
        "POSEIDON DEMETER & ATHENA",
        "POSEIDON GREEK GOD OF THE SEA",
        "POSEIDON GREEN GOD OF THE SEA",
        "POTSIE WEBER",
        "POWERPUFF GIRLS",
        "PRANCER & VIXEN",
        "PRAYING MANTIS",
        "PRIMROSE GARDENER",
        "PRINCE CHARMING",
        "PRINCE HUMPERDINCK",
        "PRINCE OF DRAGON STONE",
        "PRINCE OF DRAGONSTONE",
        "PRINCE PHILLIP",
        "PRINCE VALIANT",
        "PRINCESS AURORA",
        "PRINCESS JASMINE",
        "PRINCESS LEIA",
        "PRINCESS PEACH",
        "PRINCESSES & FAIRIES",
        "PRINCESSES AND FAIRIES",
        "PRINCIPAL SKINNER",
        "PRODIGY & SQUIRREL GIRL",
        "PROFESSOR DUMBLEDORE",
        "PROFESSOR PLUM & MRS PEACOCK",
        "PROFESSOR PLUM & MRS. PEACOCK",
        "PROFESSOR X",
        "PROFESSOR ZOOM",
        "PROTAGONIST",
        "PROTEUS",
        "PSYCHE & EROS",
        "PSYCHOLOGIST ROBERT HARTLEY",
        "PUFF THE MAGIC DRAGON",
        "PUNCH & JUDY",
        "PUNISHER",
        "PUNKY BREWSTER",
        "PUNXSUTAWNEY PHIL",
        "PUSHCART VENDOR",
        "QUEEN CERSEI LANNISTER",
        "QUEEN CERSEI OF LANNISTER",
        "QUEEN GUINEVERE",
        "QUEEN OF HEARTS",
        "QUEEN RAVEENA",
        "QUEEN RAVENNA",
        "QUICK DRAW MCGRAW",
        "QUICKSILVER",
        "QUINN KING",
        "QUINT",
        "QUORRA",
        "RACHEL GOLDBERG",
        "RACHEL ROTH'S ALTER EGO RAVEN",
        "RADAR O'REILLY",
        "RAGGEDY ANN",
        "RAGGEDY ANN & ANDY",
        "RAGNAR & ROLLO",
        "RAINBOW BRITE",
        "RAJ KOOTHRAPPALI",
        "RALPHIE PARKER FROM A CHRISTMAS STORY",
        "RAMBO",
        "RAPUNZEL",
        "RAYLAN GIVENS",
        "RAYMOND BABBITT",
        "REBECCA HOWE",
        "RED RAVEN",
        "RED SKULL",
        "REED RICHARDS",
        "REGINA MILLS",
        "RHETT BUTLER & SCARLETT O'HARA",
        "RHETT BUTLER AND SCARLETT O'HARA",
        "RICHARD CASTLE",
        "RICHIE CUNNINGHAM",
        "RICHIE RICH",
        "RICKY RICARDO",
        "RILEY & MAYA",
        "RIN TIN TIN",
        "RIP VAN WINKLE",
        "ROAD RUNNER",
        "ROBB STARK",
        "ROBBIE DOUGLAS",
        "ROBIN HOOD",
        "ROBIN HOOD & FRIAR TUCK",
        "ROBIN THE BOY WONDER",
        "ROBINSON CRUSOE",
        "ROCKET RACCOON",
        "ROCKY & ADRIAN BALBOA",
        "ROCKY & BULLWINKLE",
        "ROCKY AND ADRIAN BALBOA",
        "ROCKY AND BULLWINKLE",
        "ROCKY BALBOA",
        "RODERIGO & IAGO",
        "ROGER MURTAUGH",
        "ROGER RABBIT",
        "ROMAN GODDESS",
        "ROMAN GODDESS VENUS",
        "ROMAN GODS",
        "ROMEO AND JULIET",
        "ROMULANS",
        "ROMULUS",
        "ROMULUS AND REMUS",
        "RON BURGUNDY & BRICK TAMLAND",
        "RONALD MCDONALD",
        "RORY GILMORE",
        "ROSE NYLUND",
        "ROSEANNE CONNER",
        "ROXIE HART",
        "ROXY HART",
        "RUDOLPH THE RED-NOSED REINDEER",
        "RUFUS HUMPHREY",
        "RULER OF THE SEA",
        "RUTH LANGMORE",
        "RYLEE ADAMSON",
        "SABRETOOTH",
        "SABRINA THE TEENAGE WITCH",
        "SAD CLOWN",
        "SAILOR MOON",
        "SALLY BOWLES FROM CABARET",
        "SAM DRUCKER",
        "SAM HEALY",
        "SAM MALONE & COACH",
        "SAM MALONE & DIANE CHAMBERS",
        "SAMANTHA JONES",
        "SAMANTHA STEPHENS",
        "SAMWISE GANGEE",
        "SANCHO PANZA",
        "SANDMAN",
        "SANSA STARK",
        "SANTA & HIS ELVES",
        "SANTA & HIS FLYING REINDEER",
        "SANTA & MRS. CLAUS",
        "SANTA CLAUS",
        "SANTA CLAUS & HIS ELVES",
        "SANTA CLAUS & THE EASTER BUNNY",
        "SANTA CLAUS AND HIS ELVES",
        "SANTA CLAUSE & HIS ELVES",
        "SANTA'S REINDEER",
        "SANTA'S ELVES",
        "SARA THIBAULT",
        "SARAH ASHBURN",
        "SARAH CONNER",
        "SARAH CONNOR",
        "SARAH LEWIS",
        "SARUMAN",
        "SATURN & CRONUS",
        "SAWYER & JULIET",
        "SAYID JARRAH",
        "SCALY DRAGONS",
        "SCARLET WITCH",
        "SCARLETT & RHETT",
        "SCARLETT O'HARA",
        "SCARY CLOWNS",
        "SCARY CREATURE",
        "SCARY GHOSTS",
        "SCARY OGRES AND FRIENDLY SPRITES",
        "SCARY WEREWOLVES",
        "SCHOOL MASCOT",
        "SCOOBY DOO",
        "SCOOBY-DOO",
        "SCOOBY-DOO & SCRAPPY-DOO",
        "SCOOBY-DOO & SHAGGY BEING CHASED BY MONSTERS",
        "SCRAPPY-DOO",
        "SCREAM QUEEN",
        "SCREAM QUEENS",
        "SCROOGE MCDUCK",
        "SEA BANDITS",
        "SEA SERPENTS",
        "SEA-MONSTER GODDESS",
        "SEBASTIAN DANGERFIELD",
        "SEBASTIAN SHAW",
        "SEINFELD'S FRIEND GEORGE COSTANZA",
        "SENECA CRANE",
        "SENSE OF EQUILIBRIUM",
        "SERENA JOY",
        "SETH BULLOCK",
        "SEVEN OF NINE",
        "SHAGGY & SCOOBY DOO",
        "SHAGGY & SCOOBY-DOO",
        "SHAGGY AND VELMA",
        "SHAPESHIFTERS",
        "SHARON CARTER",
        "SHAWN SPENCER",
        "SHAZAM",
        "SHE- HULK",
        "SHE WOLF",
        "SHE-HULK",
        "SHEILA & JOEL HAMMOND",
        "SHEILA SHAY",
        "SHELDON COOPER & AMY FARRAH FOWLER",
        "SHELDON COOPER AND AMY FARRAH FOWLER",
        "SHERE KHAN",
        "SHERIFF OF NOTTINGHAM",
        "SHERIFF STILINSKI",
        "SHERLOCK HEMLOCK",
        "SHERLOCK HOLMES",
        "SHERLOCK HOLMES & DR. WATSON",
        "SHERLOCK HOLMES & WATSON",
        "SHE-WOLF",
        "SHIRLEY FEENEY",
        "SHREK & PRINCESS FIONA",
        "SHREK AND PRINCESS FIONA",
        "SHYLOCK AND ANTONIO",
        "SIDESHOW BOB",
        "SIENA ROSSO",
        "SIGGY HARALDSON",
        "SILVER SURFER",
        "SILVIO DANTE",
        "SIMON BASSETT",
        "SINBAD THE SAILOR",
        "SINESTRO",
        "SINISTER GARGOYLES",
        "SIR GALAHAD",
        "SIR JOHN FALSTAFF",
        "SIR LANCELOT",
        "SIR LIONEL & SIR LUCAN",
        "SIR PALAMEDES",
        "SIR PERCIVAL & SIR GARETH",
        "SIR PERCIVAL AND SIR GARETH",
        "SIR TOR & SIR TRISTAN",
        "SKELETONS & GHOULS",
        "SLEEPING BEAUTY",
        "SLEEPING BEAUTY & THE FROG",
        "SLEEPING BEAUTY & THE PRINCE",
        "SLEIPNIR THE EIGHT - LEGGED HORSE",
        "SLEIPNIR THE EIGHT LEGGED HORSE",
        "SLEIPNIR THE EIGHT-LEGGED HORSE",
        "SLOAN SABBITH",
        "SMOKEY BEAR",
        "SMOKEY THE BEAR",
        "SMURFETTE",
        "SNOOPY",
        "SNOOPY & WOODSTOCK",
        "SNOW WHITE",
        "SNOW WHITE & ROSE RED",
        "SNOW WHITE'S STEPMOTHER",
        "SOFIA RODRIGUEZ",
        "SONIC THE HEDGEHOG",
        "SOPHIA PETRILLO",
        "SORCERER & SORCERESS",
        "SPACE ALIEN",
        "SPACE CREATURES",
        "SPACE GHOST",
        "SPACE PIRATE NEBULA",
        "SPANKY",
        "SPANKY ALFALFA & DARLA",
        "SPANKY",
        "ALFALFA",
        "& DARLA",
        "SPANKY",
        "ALFALFA",
        "BUCKWHEAT",
        "& DARLA",
        "SPECTERS & SPIRITS",
        "SPEED BUGGY",
        "SPEED RACER",
        "SPEED RACER & TRIXIE",
        "SPELLBINDING UNICORN",
        "SPENCE WESTMORE",
        "SPIDER MAN",
        "SPIDER MAN'S ALTER-EGO PETER PARKER",
        "SPIDER-GIRL",
        "SPIDER-MAN",
        "SPIDER-MAN VILLAIN SANDMAN",
        "SPIDER-WOMAN",
        "SPOCK & KIRK",
        "SPONGE BOB SQUARE PANTS",
        "SPONGEBOB SQUAREPANTS",
        "SPOOKY PHANTOM",
        "SPOOKY SCARECROW",
        "SPOOKY SKELETONS",
        "SPY KIDS' THUMB THUMB",
        "SQUIDWARD TENTACLES",
        "STAGGERING ZOMBIE",
        "STAGGERING ZOMBIES",
        "STANLEY KOWALSKI",
        "STATURE",
        "STAY PUFT MARSHMALLOW MAN",
        "STEPHANIE PLUM",
        "STEVE MCGARRETT",
        "STEVE ROGERS",
        "STEVE URKEL",
        "STEVEN QUARTZ UNIVERSE",
        "STEWIE GRIFFIN",
        "STILES STILINSKI",
        "STORM GIANTS",
        "STORM SHADOW",
        "STORMTROOPER",
        "STRAWBERRY SHORTCAKE",
        "SUE STORM",
        "SUGARPLUM FAIRIES",
        "SUGAR-PLUM FAIRIES",
        "SUN-HWA KWON",
        "SUNNY DAYS",
        "SUPER FRIENDS",
        "SUPERBOY",
        "SUPERGIRL",
        "SUPERHERO",
        "SUPERHEROES",
        "SUPERMAN",
        "SUPERMAN & LOIS LANE",
        "SUPERMAN'S ARCH ENEMY LEX LUTHOR",
        "SUPERNATURAL BEING",
        "SUPERNATURAL BEINGS",
        "SUPERNATURAL CREATURES",
        "SUPERNATURAL SUPERHERO",
        "SUZANNE SUGARBAKER",
        "SWAMP CREATURE",
        "SWAMP MONSTER",
        "SWASHBUCKLER",
        "SWASHBUCKLING BUCCANEER",
        "SWASHBUCKLING CAPTAIN JACK SPARROW",
        "SWASHBUCKLING PIRATE",
        "SWEATERS & FLEECES",
        "SWEATHOGS",
        "SWEET POLLY PUREBRED",
        "SWORDSMAN",
        "SYLVESTER & TWEETY",
        "SYLVESTER AND THE MAGIC PEBBLE",
        "SYLVESTER THE CAT",
        "SYLVIA TILLY",
        "SYNTH MAX",
        "SYNTHETIC HUMANOID VISION",
        "TALIA AL GHUL",
        "TALKING ANIMALS",
        "TAMI TAYLOR",
        "TARZAN & JANE",
        "TARZAN AND JANE",
        "TAZMANIAN DEVIL",
        "TED BAXTER & LOU GRANT",
        "TEDDY DUNCAN",
        "TEDDY FAY",
        "TEDDY RUXPIN",
        "TEENAGE MUTANT NINJA TURTLES",
        "TELESTRATIONS",
        "TENNESSEE TUXEDO",
        "TESS OCEAN",
        "TESSA ALTMAN",
        "THALIA THE MUSE",
        "THANOS",
        "THE ABOMINABLE SNOWMAN",
        "THE AMAZING SPIDER-MAN",
        "THE ANCIENT GOD NUN",
        "THE ANCIENT GODDESS NUT",
        "THE ARTFUL DODGER",
        "THE BEAUTIFUL PRINCESS",
        "THE BIG BAD WOLF",
        "THE BLUE FAIRY",
        "THE BLUTH FAMILY",
        "THE BOBBSEY TWINS",
        "THE BOOGEYMAN",
        "THE BOY WONDER",
        "THE BYRDE FAMILY",
        "THE CENTAURS",
        "THE CHESHIRE CAT",
        "THE CHESHIRE CAT & THE QUEEN OF HEARTS",
        "THE CHESHIRE CAT AND THE QUEEN OF HEARTS",
        "THE COWARDLY LION",
        "THE CRAWLEY FAMILY",
        "THE CREW OF THE STARSHIP ENTERPRISE",
        "THE CRIMSON KING",
        "THE CYLONS",
        "THE DARLING CHILDREN",
        "THE DODO",
        "THE DORMOUSE",
        "THE DOWNTON STAFF",
        "THE DRAUGR",
        "THE DUNCAN FAMILY",
        "THE EVIL QUEEN",
        "THE EVIL WITCH & THE GOOD PRINCESS",
        "THE EVIL WITCH AND THE GOOD PRINCESS",
        "THE FANTASTIC FOUR",
        "THE FARMER AND THE STORK",
        "THE FEATHERINGTON FAMILY",
        "THE FLASH",
        "THE FLASH VILLAIN ZOOM",
        "THE FLINSTONES AND THE RUBBLES",
        "THE FLINT STONES & THE RUBBLES",
        "THE FLINTSTONES & THE RUBBLES",
        "THE FROG PRINCE",
        "THE FURIES",
        "THE GEICO GECKO",
        "THE GENIE IN THE MAGIC MIRROR",
        "THE GHOST OF CHRISTMAS PAST",
        "THE GHOSTS OF CHRISTMAS PAST PRESENT & YET-TO-COM",
        "THE GHOSTS OF CHRISTMAS PAST PRESENT AND YET-TO-COM",
        "THE GINGERBREAD MAN",
        "THE GOD ATLAS",
        "THE GODDESS HERA",
        "THE GODDESS ISIS",
        "THE GODDESS NEPHTHYS",
        "THE GOOSE GIRL",
        "THE GOOSE THAT LAID THE GOLDEN EGGS",
        "THE GORGONS",
        "THE GREAT GAZOO",
        "THE GREAT GONZO",
        "THE GREEK GOD APOLLO",
        "THE GREEN KNIGHT",
        "THE GRIM REAPER",
        "THE GRINCH",
        "THE GRINCH AND CINDY LOU WHO",
        "THE GRINCH WHO STOLE CHRISTMAS",
        "THE GRISWOLDS",
        "THE GRYPHON",
        "THE HARE AND THE TORTOISE",
        "THE HUMAN TORCH",
        "THE HUNTSMAN",
        "THE INCREDIBLE HULK",
        "THE JOKER",
        "THE JUSTICE LEAGUE",
        "THE KID",
        "THE KNIGHT KING",
        "THE KRAKEN",
        "THE LANNISTER FAMILY",
        "THE LITTLE PRINCE",
        "THE LONE RANGER",
        "THE LONE RANGER & TONTO",
        "THE MAD HATTER",
        "THE MAN IN BLACK",
        "THE MAN IN THE MOON",
        "THE MAN IN THE YELLOW HAT",
        "THE MAN IN YELLOW HAT",
        "THE MAN WITH NO NAME",
        "THE MINOTAUR",
        "THE MOCK TURTLE",
        "THE MONSTER UNDER THE BED",
        "THE MUPPETS",
        "THE NIGHT KING",
        "THE NIGHT'S WATCH",
        "THE NINE MUSES",
        "THE NINE MUSES OF GREEK MYTHOLOGY",
        "THE OLD WOMAN WHO LIVED IN A SHOE",
        "THE ORACLE AT DELPHI",
        "THE PEANUTS GANG",
        "THE PEANUTS KIDS",
        "THE PIED PIPER",
        "THE PIED PIPER OF HAMELIN",
        "THE PINK LADIES",
        "THE PINK PANTHER",
        "THE POWERPUFF GIRLS",
        "THE PRINCESS & A FROG",
        "THE PRINCESS AND A FROG",
        "THE PROTAGONIST OF THE STORY",
        "THE QUEEN OF HEARTS",
        "THE RED QUEEN",
        "THE RED WOMAN",
        "THE RIDDLER & THE JOKER",
        "THE ROAD RUNNER",
        "THE SANDERSON SISTERS",
        "THE SCARECROW FROM THE WONDERFUL WIZARD OF OZ",
        "THE SEA GOD POSEIDON",
        "THE SHERIFF OF NOTTINGHAM",
        "THE SHOEMAKER & THE ELVES",
        "THE SMURFS",
        "THE SPECTACULAR SPIDER-MAN",
        "THE STARK FAMILY",
        "THE STEELE BROTHERS",
        "THE SUGAR PLUM FAIRY",
        "THE THORNBERRY FAMILY",
        "THE THREE GRACES",
        "THE THREE LITTLE PIGS",
        "THE THREE MUSKETEERS",
        "THE TOOTH FAIRY",
        "THE TORTOISE & THE HARE",
        "THE TROLL WHO LIVED UNDER THE BRIDGE",
        "THE TWELVE OLYMPIANS",
        "THE UPPER GREAT LAKES REGION",
        "THE VALKYRIES",
        "THE WHITE RABBIT",
        "THE WHITE WITCH",
        "THE WICKED WITCH OF THE WEST",
        "THE WILD THINGS",
        "THE WILDLINGS",
        "THE WITCHES OF MACBETH",
        "THE WOLF & RED RIDING HOOD",
        "THE WOLF AND RED RIDING HOOD",
        "THEA QUEEN",
        "THELMA AND VINTON HARPER",
        "THELMA EVANS",
        "THESEUS & HIPPOLYTA",
        "THESEUS & THE MINOTAUR",
        "THESEUS AND THE MINOTAUR",
        "THOMAS THE TANK ENGINE",
        "THOR",
        "THOR & TYR",
        "THOR THE GOD OF THUNDER",
        "THOR VILLAIN LOKI",
        "THREE BLIND MICE",
        "THREE HEADED MONSTERS",
        "THREE-HEADED DOG",
        "THREE-HEADED MONSTER",
        "THUMBELINA",
        "THUMBLING",
        "THUMPER & BAMBI",
        "THUNDERCATS",
        "TIM RIGGINS",
        "TINA BELCHER",
        "TINKER BELL",
        "TINKERBELL",
        "TINY ELVES",
        "TINY TIM",
        "TITANS & TITANESSES",
        "TOBIAS RAGG",
        "TOM & JERRY",
        "TOM & SUMMER",
        "TOM AND JERRY",
        "TOM BUCHANAN",
        "TOM SAWYER",
        "TOM SAWYER & BECKY THATCHER",
        "TOM THUMB",
        "TONY SOPRANO",
        "TONY STARK'S ALTER EGO IRON MAN",
        "TONY THE TIGER",
        "TOOTH FAIRY",
        "TOP CAT",
        "TOUCAN SAM",
        "TREVOR FITZROY",
        "TRIBAL WARRIOR",
        "TROLL KINGS",
        "TROY BOLTON",
        "TURANGA LEELA",
        "TWEEDLEDUM & TWEEDLEDEE",
        "TWEETY BIRD",
        "TWITTER BIRD",
        "TWO-FACE & KINGPIN",
        "TWO-HEADED CREATURE",
        "TWO-HEADED MONSTER",
        "TYLER DURDEN",
        "TYRION LANNISTER",
        "UHTRED OF BEBBANBURG",
        "UNCLE JESSE DUKE",
        "UNCLE SAM",
        "UNDERGROUND CAVE",
        "UNICORN",
        "UNICORNS",
        "UNICORNS & DRAGONS",
        "URANIA THE MUSE",
        "URANUS GOD OF THE SKY",
        "URSULA MERKLE",
        "URSULA THE SEA WITCH",
        "URSULA THE SEAWITCH",
        "VALDINE WINGFIELD",
        "VALERIE GAIL",
        "VAMPIRE",
        "VAMPIRE FREAKING OUT AT A RAY OF SUNLIGHT",
        "VAMPIRE JUMPING OUT OF A COFFIN",
        "VAMPIRE-HUNTER BLADE",
        "VAMPIRES & ZOMBIES",
        "VAMPIRES WITCHES & GHOSTS",
        "VAMPIRES",
        "WITCHES & GHOSTS",
        "VANIR",
        "VENUS THE GODDESS OF LOVE & BEAUTY",
        "VERONICA & BETTY",
        "VERONICA QUAIFE",
        "VICKI VALE",
        "VICTOR FRANKENSTEIN",
        "VICTORIA BARKLEY",
        "VICTORIA GRAYSON",
        "VIKING CREATURE",
        "VILLAINS WE LOVE TO HATE",
        "VINNIE BARBARINO",
        "VIRTUAL ANIMALS",
        "VIRTUAL PETS",
        "VIVIAN WARD & EDWARD LEWIS",
        "VULCAN THE GOD OF FIRE",
        "VULCANS",
        "WACKY SITCOM NEIGHBORS",
        "WALLY CLEAVER",
        "WALT COMEAU",
        "WALTER SKINNER",
        "WALTER WHITE",
        "WARD & JUNE CLEAVER",
        "WARLOCKS & WITCHES",
        "WARRANT OFFICER ELLEN RIPLEY",
        "WARREN WORTHINGTON III",
        "WATER SPIRITS",
        "WEDNESDAY & PUGSLEY ADDAMS",
        "WEDNESDAY AND PUGSLEY ADDAMS",
        "WENDY & PETER PAN",
        "WENDY AND PETER PAN",
        "WEREWOLF",
        "WEREWOLVES & MONSTERS",
        "WEREWOLVES VAMPIRES & GHOSTS",
        "WEREWOLVES",
        "VAMPIRES & GHOSTS",
        "WHIMSICAL ELVES",
        "WHIMSICAL REINDEER",
        "WHITE LYCAN",
        "WHITE QUEEN",
        "WHITE WALKERS",
        "WICKED STEPMOTHER",
        "WICKED WITCH",
        "WICKED WITCH OF THE WEST",
        "WILBUR THE PIG",
        "WILD CREATURES",
        "WILE E. COYOTE",
        "WILL ROBINSON",
        "WILL TRUMAN & GRACE ADLER",
        "WILLOW ROSENBERG",
        "WILLY WONKA",
        "WILMA & PEBBLES FLINTSTONE",
        "WILMA FLINTSTONE",
        "WILMA FLINTSTONE & BETTY RUBBLE",
        "WINGED CREATURES",
        "WINGED MONKEYS",
        "WINGED MONSTERS",
        "WINIFRED MARY & SARAH SANDERSON",
        "WINN SCHOTT",
        "WINNIE THE POOH",
        "WINNIE-THE-POOH",
        "WINSTON BISHOP",
        "WISE OLD OWL",
        "WISE SAMURAI",
        "WISE SAMURI",
        "WITCH DOCTOR",
        "WITCHES & SPRITES",
        "WITCHES & WIZARDS",
        "WITCHES AROUND A BOILING CAULDRON",
        "WIZARD OF OZ",
        "WIZARDS & WARLOCKS",
        "WOLVERINE",
        "WOLVERINE & MYSTIQUE",
        "WOLVERINE & PROFESSOR X",
        "WOLVERINE & STORM",
        "WOLVERINE & THE X-MEN",
        "WONDER GIRL",
        "WONDER WOMAN",
        "WOOD NYMPHS",
        "WOODLAND SPRITES & PIXIES",
        "WOODSTOCK",
        "WOODY BOYD",
        "WOODY WOODPECKER",
        "XANDER HARRIS",
        "X-MEN",
        "X-MEN VILLAIN MAGENTO",
        "X-MEN VILLAIN MAGNETO",
        "YODA",
        "YOGI BEAR",
        "YOGI BEAR & BOO BOO",
        "YORICK",
        "YOSEMITE SAM",
        "YOSHI & TOAD",
        "YOUNG HOBBIT",
        "ZACK & KELLY",
        "ZANY HOUSEWIFE",
        "ZENDAYA IN EUPHORIA",
        "ZERO THE HERO",
        "ZEUS",
        "ZEUS & APHRODITE",
        "ZEUS & HERA",
        "ZEUS KING OF THE GODS",
        "ZEUS: LEADER OF THE OLYMPIC GODS",
        "ZIGGY",
        "ZIGGY STARDUST",
        "ZOILA DIAZ",
        "ZOMBIES",
        "ZORRO"
    ]
};