const the_70sData = {
    category: "THE 70'S",
    puzzles: [
        "APPLE STARTS PRODUCING PERSONAL COMPUTERS",
        "BELL-BOTTOM JEANS WITH PLATFORM SHOES",
        "BREAKFAST IN AMERICA",
        "EGYPT & ISRAEL SIGN HISTORIC PEACE TREATY",
        "EVITA & A CHORUS LINE ARE BROADWAY HITS",
        "FIRST TEST-TUBE BABY BORN",
        "GROOVY CLOTHING",
        "I CAN SEE CLEARLY NOW BY JOHNNY NASH",
        "LIVELY DISCOTHEQUE",
        "MARK SPITZ WINS SEVEN OLYMPIC GOLD MEDALS",
        "PLAYING SIMON",
        "POP ROCKS & COCA-COLA",
        "ROLLER-DISCO PARTIES",
        "SATURDAY MORNING CARTOONS",
        "SATURDAY NIGHT FEVER & GREASE",
        "SEA-MONKEYS",
        "SHORT SHORTS & TUBE SOCKS",
        "SHORT-SHORTS & TUBE SOCKS",
        "STATION WAGONS WITH WOOD TRIM",
        "THE U.S. CELEBRATES ITS BICENTENNIAL",
        "U.S. SIGNS TREATY RETURNING PANAMA CANAL",
        "WALT DISNEY LAND OPENS IN ORLANDO"
    ]
};