const the_50sData = {
    category: "THE 50'S",
    puzzles: [
        "ALASKA BECOMES THE FORTY-NINTH STATE",
        "BUFFALO BOB SMITH HOWDY DOODY & CLARABELL",
        "CHEVY INTRODUCES THE CORVETTE",
        "GENE KELLY SINGS IN THE RAIN",
        "GREGORY PECK STARS IN THE BIG COUNTRY",
        "GROUCHO'S YOU BET YOUR LIFE",
        "MARILYN MONROE MARRIES JOE DIMAGGIO",
        "PEGGY SUE BY BUDDY HOLLY",
        "THE KOREAN WAR"
    ]
};